name: Trigger auto deployment for movie-poster-svc-b76s6utvi44xo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/movie-poster-svc-b76s6utvi44xo-AutoDeployTrigger-666b3c04-3100-4a86-a2e9-35d23b7e51c3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MOVIEPOSTERSVCB76S6UTVI44XO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MOVIEPOSTERSVCB76S6UTVI44XO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MOVIEPOSTERSVCB76S6UTVI44XO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}src/toto
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: azrambiacrb76s6utvi44xo.azurecr.io
          registryUsername: ${{ secrets.MOVIEPOSTERSVCB76S6UTVI44XO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MOVIEPOSTERSVCB76S6UTVI44XO_REGISTRY_PASSWORD }}
          containerAppName: movie-poster-svc-b76s6utvi44xo
          resourceGroup: azrambi
          imageToBuild: azrambiacrb76s6utvi44xo.azurecr.io/movie-poster-svc-b76s6utvi44xo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


